### ISSUE TITLE
Sidebar being too huge \ Боковая панель слишком большая

### ISSUE THREAD

**Issue by gitgernit** [Data-Name-ID/yandex-lms-dark-theme#1]
# The sidebar panel is huger than it is supposed to be upon opening it while in LMS code editor. 

# Боковая панель, открывающаяся в редакторе кода ЛМС слишком большая.
![stylebot_lms_dark_theme_bug](https://github.com/Data-Name-ID/yandex-lms-dark-theme/assets/129539613/b1a25b74-a0dd-4f75-aeeb-e5752e00abb0)

**Comment by Data-Name-ID** [comment]
Это особенность добавлена специально, если вам не нужно это, закомментируйте или удалите следующий код:

```css
.sideblock {
    max-width: 85vw;
}
```
